nav:
  - Home: index.md
  - Blog: 
      - blog/2020-12-01-numba.md
      - blog/2021-05-06-tf.md
      - blog/2021-06-18-srun.md
      - blog/2022-02-02-Changes_to_Slurm_srun_for_interactive_jobs.md
      - blog/2022-10-04-python2to3.md
      - blog/2022-03-05-local-io-performance.md
      - blog/2022-12-19-windows_ssh.md
      - blog/2023-01-10-using_specific_module_versions_on_hpc.md
  - Documentation:
      - Documentation Home: Documentation/index.md
      - Getting Started: Documentation/getting_started.md
      - Help and Support: Documentation/help.md
      - Systems: 
        - Systems: Documentation/Systems/index.md
        - Kestrel: 
          - Documentation/Systems/Kestrel/index.md
          - Documentation/Systems/Kestrel/running.md
          - Documentation/Systems/Kestrel/modules.md
          - Documentation/Systems/Kestrel/filesystems.md
        - Eagle: 
          - Documentation/Systems/Eagle/index.md
          - Running on Eagle: 
            - Documentation/Systems/Eagle/Running/index.md
            - Partitions and Scheduling: Documentation/Systems/Eagle/Running/eagle_partitions.md
            - Job Priorities: Documentation/Systems/Eagle/Running/eagle_job_priorities.md
            - Batch Jobs: Documentation/Systems/Eagle/Running/batch_jobs.md
            - Interactive Jobs: Documentation/Systems/Eagle/Running/interactive_jobs.md
            - Multiple Sub-Jobs: Documentation/Systems/Eagle/Running/multiple_sub_jobs.md
            - Sample Batch Scripts: Documentation/Systems/Eagle/Running/sample_sbatch.md
            - Debugging at Scale: Documentation/Systems/Eagle/Running/debugging_at_scale.md
            - Monitor and Control Commands: Documentation/Systems/Eagle/Running/monitor_and_control.md
          - Modules: Documentation/Systems/Eagle/modules.md
          - Documentation/Systems/Eagle/lustrebestpractices.md
        - Swift:
          - Documentation/Systems/Swift/index.md
          - Documentation/Systems/Swift/running.md
          - Documentation/Systems/Swift/modules.md
          - Documentation/Systems/Swift/filesystems.md
        - Vermilion:
          - Documentation/Systems/Vermilion/index.md
          - Documentation/Systems/Vermilion/running.md
          - Documentation/Systems/Vermilion/modules.md
          - Documentation/Systems/Vermilion/filesystems.md
      - Managing your Data:
        - Unix File Permissions: Documentation/Managing_Data/file_permissions.md
        - Mass Storage System: Documentation/Managing_Data/mss.md
        - Transferring Files:
          - Documentation/Managing_Data/Transferring_Files/index.md
          - Documentation/Managing_Data/Transferring_Files/FileZilla.md
          - Documentation/Managing_Data/Transferring_Files/globus.md
          - Documentation/Managing_Data/Transferring_Files/winscp.md
      - Environment:
          - Shell Startup: Documentation/Environment/shell.md
          - Lmod: Documentation/Environment/lmod.md
          # - Customization:
              #  - Spack Environments: Documentation/Environment/Customization/spack.md
          - Conda: Documentation/Environment/Customization/conda.md
              #  - Container Environments: Documentation/Environment/Customization/containers.md
          - Building an Application: 
            - Documentation/Environment/Building_Packages/index.md
            - Documentation/Environment/Building_Packages/acquire.md
            - Documentation/Environment/Building_Packages/config_make_install.md
            - Documentation/Environment/Building_Packages/modules.md
      - Applications:
          # - Templates:
          #   - Example Page: Documentation/Applications/Templates/berkeleygw_example.md
          #   - Blank Template: Documentation/Applications/Templates/applications_template.md
          - ANSYS CFD:  Documentation/Applications/ansys.md
          - COMSOL:     Documentation/Applications/comsol.md
          - FEniCS:     Documentation/Applications/fenics.md
          - GAMS:       Documentation/Applications/gams.md
          - Gaussian:   Documentation/Applications/gaussian.md
          - Gurobi:     Documentation/Applications/gurobi.md
          - LAMMPS:     Documentation/Applications/lammps.md
          - MATLAB:
            - Documentation/Applications/Matlab/index.md
            - Batch Mode: Documentation/Applications/Matlab/batch.md
            - Interactive Mode: Documentation/Applications/Matlab/interactive.md
            - Parallel Computing Toolbox: Documentation/Applications/Matlab/parallel.md
            - Versions and Licenses: Documentation/Applications/Matlab/versions.md
          - Q-Chem:     Documentation/Applications/qchem.md
          - STAR-CCM+:  Documentation/Applications/starccm.md
          - VASP:       Documentation/Applications/vasp.md
          - WRF:        Documentation/Applications/wrf.md
      - Development:
         - Languages:
             - Julia:
                  - Documentation/Development/Languages/Julia/index.md
                  - Documentation/Development/Languages/Julia/julia_install.md
                  - Documentation/Development/Languages/Julia/julia_tour.md
                  - Documentation/Development/Languages/Julia/julia_parallel.md
                  - Documentation/Development/Languages/Julia/julia_ccall_pycall.md
             - C++:     Documentation/Development/Languages/c++.md
             - R:       Documentation/Development/Languages/r.md
             - Bash:    Documentation/Development/Languages/bash.md
             - Fortran: 
               - Documentation/Development/Languages/Fortran/index.md
               - Advanced: Documentation/Development/Languages/Fortran/f90_advanced.md
             - Python:
                  - Documentation/Development/Languages/Python/index.md
                  - Documentation/Development/Languages/Python/dask.md
         - Jupyter: 
             - Documentation/Development/Jupyter/index.md
             - JupyterHub: Documentation/Development/Jupyter/jupyterhub.md
         - Programming Models:
              # - Documentation/Development/Programming_Models/index.md
              - MPI: Documentation/Development/Programming_Models/mpi.md
              # - OpenMP: Documentation/Development/Programming_Models/openmp.md
              # - OpenACC: Documentation/Development/Programming_Models/openacc.md
                #- CUDA:    Documentation/Development/Programming_Models/cuda.md
         - Compilers: Documentation/Development/Compilers/rosetta_stone.md
              # - GNU  : Documentation/Development/Compilers/gnu.md
              # - Intel: Documentation/Development/Compilers/intel.md
              # - NVHPC: Documentation/Development/Compilers/nvhpc.md
              # - AOCC : Documentation/Development/Compilers/aocc.md
              # - Cray : Documentation/Development/Compilers/cray.md
              # - Rosetta Stone<br> of Compilers : Documentation/Development/Compilers/rosetta_stone.md
         - Build Tools:
              - CMake : Documentation/Development/Build_Tools/cmake.md
              - Spack : Documentation/Development/Build_Tools/spack.md
              - Git :   Documentation/Development/Build_Tools/git.md
         - Libraries:
              - Documentation/Development/Libraries/index.md
              - Libraries How-to:   Documentation/Development/Libraries/howto.md
              - FFTW:   Documentation/Development/Libraries/fftw.md
              - HDF5:   Documentation/Development/Libraries/hdf5.md
              - HSL:  Documentation/Development/Libraries/hsl.md
              - IPOPT: Documentation/Development/Libraries/ipopt.md
              - LAPACK and ScaLAPACK: Documentation/Development/Libraries/lapack.md
              - LibSci: Documentation/Development/Libraries/libsci.md
              - MKL:    Documentation/Development/Libraries/mkl.md
              # - NetCDF: Documentation/Development/Libraries/netcdf.md
              # - PETSc:  Documentation/Development/Libraries/petsc.md
         - Performance Tools:
            #  - ARM Performance Reports:
            #    - Documentation/Development/Performance_Tools/ARM/index.md
            #    - MAP : Documentation/Development/Performance_Tools/ARM/map.md
            #    - Performance Reports: Documentation/Development/Performance_Tools/ARM/performance_rep.md
             - Intel Parallel Studio:
               - Documentation/Development/Performance_Tools/Intel/index.md
              #  - Trace Analyzer: Documentation/Development/Performance_Tools/Intel/trace.md
              #  - VTune : Documentation/Development/Performance_Tools/Intel/vtune.md
            #  - CrayPat: Documentation/Development/Performance_Tools/craypat.md
            #  - HPCToolkit: Documentation/Development/Performance_Tools/hpctoolkit.md
         - Debug Tools:
            #  - ARM:
            #    - Documentation/Development/Debug_Tools/ARM/index.md
            #    - DDT: Documentation/Development/Debug_Tools/ARM/ddt.md
             - GDB: Documentation/Development/Debug_Tools/gdb.md
               #- Inspector: Documentation/Development/Debug_Tools/Debug/inspector.md
               #- Valgrind:  Documentation/Development/Debug_Tools/Debug/valgrind.md
         - Containers:
            - Documentation/Development/Containers/index.md
            - Documentation/Development/Containers/registres.md
            - Documentation/Development/Containers/singularity.md
      - Visualization and Analytics:
         - Documentation/Viz_Analytics/index.md
         - VirtualGL and FastX: Documentation/Viz_Analytics/virtualgl_fastx.md 
         - Avizo: Documentation/Viz_Analytics/avizo.md
         - Paraview: Documentation/Viz_Analytics/paraview.md
         - VisIT: Documentation/Viz_Analytics/visit.md
      - Machine Learning:
           - Documentation/Machine_Learning/index.md 
           - Reinforcement Learning: Documentation/Machine_Learning/Reinforcement_Learning/index.md
           - TensorBoard: Documentation/Machine_Learning/TensorBoard/index.md
           - Containerized TensorFlow: Documentation/Machine_Learning/Containerized_TensorFlow/index.md
  - Kestrel Friendly Users:
      - Getting Started:
        - Friendly_User/Getting_Started/index.md
        - Known Issues: Friendly_User/Getting_Started/known_issues.md
      - Environments:
        - Kestrel Environments Overview: Friendly_User/Environments/index.md
        - Toolchains:
          - Intel: Friendly_User/Environments/Toolchains/intel.md
        - Environments Tutorial: Friendly_User/Environments/tutorial.md
      - Applications:
        - VASP: Friendly_User/Applications/vasp.md
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: UA-189117140-2
extra_css:
  - stylesheets/extra.css
site_name: NREL HPC 
repo_url: https://github.com/NREL/HPC/tree/gh-pages
repo_name: NREL/HPC
